// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a list of potential troubleshooting steps based on an error analysis.
 *
 * - generateTroubleshootingSteps - A function that generates troubleshooting steps.
 * - GenerateTroubleshootingStepsInput - The input type for the generateTroubleshootingSteps function.
 * - GenerateTroubleshootingStepsOutput - The return type for the generateTroubleshootingSteps function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTroubleshootingStepsInputSchema = z.object({
  errorMessage: z
    .string()
    .describe('The error message or description of the access problem.'),
  errorAnalysis: z
    .string()
    .describe('The analysis of the error message to understand the problem.'),
});
export type GenerateTroubleshootingStepsInput = z.infer<
  typeof GenerateTroubleshootingStepsInputSchema
>;

const GenerateTroubleshootingStepsOutputSchema = z.object({
  troubleshootingSteps: z
    .array(z.string())
    .describe('A list of potential troubleshooting steps to resolve the error.'),
});
export type GenerateTroubleshootingStepsOutput = z.infer<
  typeof GenerateTroubleshootingStepsOutputSchema
>;

export async function generateTroubleshootingSteps(
  input: GenerateTroubleshootingStepsInput
): Promise<GenerateTroubleshootingStepsOutput> {
  return generateTroubleshootingStepsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTroubleshootingStepsPrompt',
  input: {schema: GenerateTroubleshootingStepsInputSchema},
  output: {schema: GenerateTroubleshootingStepsOutputSchema},
  prompt: `You are an expert in troubleshooting access-related errors.

  Based on the error message and its analysis, generate a list of potential troubleshooting steps that the user can follow to resolve the issue.

  Error Message: {{{errorMessage}}}
  Error Analysis: {{{errorAnalysis}}}

  Troubleshooting Steps:`,
});

const generateTroubleshootingStepsFlow = ai.defineFlow(
  {
    name: 'generateTroubleshootingStepsFlow',
    inputSchema: GenerateTroubleshootingStepsInputSchema,
    outputSchema: GenerateTroubleshootingStepsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
