export type CardStats = {
  vel: number; // Velocidad
  tir: number; // Tiro
  rit: number; // Ritmo
  reg: number; // Regate
  def: number; // Defensa
  fis: number; // Físico
};

export type Card = {
  id: number;
  name: string;
  position: 'POR' | 'DEF' | 'MED' | 'DEL';
  rarity: 'common' | 'rare' | 'epic' | 'legendary' | 'hero' | 'CRACKS' | 'LEYENDA MUNDIAL';
  stats: CardStats;
  rating: number;
  playerImageUrl: string;
  clubImageUrl: string;
  countryImageUrl: string;
};

export const allCards: Card[] = [
  {
    id: 1,
    name: 'Dibu Martinez',
    position: 'POR',
    rarity: 'legendary',
    stats: { vel: 88, tir: 52, rit: 85, reg: 58, def: 90, fis: 85 },
    rating: 90,
    playerImageUrl: 'https://i.postimg.cc/y6gMfdjq/CARTA-DIBU.png',
    clubImageUrl: 'https://i.postimg.cc/65Vwqmfd/aston-villa.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 2,
    name: 'Lionel Messi',
    position: 'DEL',
    rarity: 'legendary',
    stats: { vel: 87, tir: 95, rit: 92, reg: 98, def: 40, fis: 75 },
    rating: 97,
    playerImageUrl: 'https://i.postimg.cc/t4qZdLjc/CARTA-MESSI.png',
    clubImageUrl: 'https://i.postimg.cc/C1pTsmQn/inter-miami.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 3,
    name: 'Ángel Di María',
    position: 'DEL',
    rarity: 'epic',
    stats: { vel: 90, tir: 85, rit: 88, reg: 92, def: 50, fis: 72 },
    rating: 88,
    playerImageUrl: 'https://i.postimg.cc/BZdQQRbF/3-ANGEL-DI-MARIA.png',
    clubImageUrl: 'https://i.postimg.cc/0j7bS3Jj/benfica.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 4,
    name: 'Julián Álvarez',
    position: 'DEL',
    rarity: 'rare',
    stats: { vel: 88, tir: 86, rit: 87, reg: 84, def: 55, fis: 78 },
    rating: 84,
    playerImageUrl: 'https://i.postimg.cc/Hss3nvNp/4-julian-alvarez.png',
    clubImageUrl: 'https://i.postimg.cc/P5g1z2s9/man-city.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 5,
    name: 'Rodrigo De Paul',
    position: 'MED',
    rarity: 'rare',
    stats: { vel: 82, tir: 78, rit: 85, reg: 84, def: 75, fis: 88 },
    rating: 84,
    playerImageUrl: 'https://i.postimg.cc/fLRjyJH8/5-DE-PAUL.png',
    clubImageUrl: 'https://i.postimg.cc/VvWqJg4v/atletico-madrid.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 6,
    name: 'Leandro Paredes',
    position: 'MED',
    rarity: 'common',
    stats: { vel: 70, tir: 80, rit: 75, reg: 81, def: 78, fis: 80 },
    rating: 81,
    playerImageUrl: 'https://i.postimg.cc/3NPgt93q/6-LEANDRO-PADREDES.png',
    clubImageUrl: 'https://i.postimg.cc/W3h3X5N3/as-roma.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 7,
    name: 'Enzo Fernández',
    position: 'MED',
    rarity: 'rare',
    stats: { vel: 80, tir: 82, rit: 83, reg: 86, def: 75, fis: 81 },
    rating: 85,
    playerImageUrl: 'https://i.postimg.cc/d1NRywpw/7-ENZO-FERNADNEZ.png',
    clubImageUrl: 'https://i.postimg.cc/tCTmLP2M/chelsea.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 8,
    name: 'A. Mac Allister',
    position: 'MED',
    rarity: 'rare',
    stats: { vel: 81, tir: 83, rit: 82, reg: 85, def: 72, fis: 79 },
    rating: 84,
    playerImageUrl: 'https://i.postimg.cc/j2WH6BYN/8-MACLISTTER.png',
    clubImageUrl: 'https://i.postimg.cc/44rGvQ1p/liverpool.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 9,
    name: 'Cuti Romero',
    position: 'DEF',
    rarity: 'epic',
    stats: { vel: 80, tir: 55, rit: 82, reg: 70, def: 89, fis: 86 },
    rating: 86,
    playerImageUrl: 'https://i.postimg.cc/KvyG1y72/9-cuti-romero.png',
    clubImageUrl: 'https://i.postimg.cc/zX8ZgGgD/tottenham.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 10,
    name: 'N. Otamendi',
    position: 'DEF',
    rarity: 'rare',
    stats: { vel: 72, tir: 60, rit: 75, reg: 68, def: 88, fis: 87 },
    rating: 83,
    playerImageUrl: 'https://i.postimg.cc/7ZHqNMQt/10-NICOLAS-OTAMENDI.png',
    clubImageUrl: 'https://i.postimg.cc/0j7bS3Jj/benfica.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 11,
    name: 'Nahuel Molina',
    position: 'DEF',
    rarity: 'common',
    stats: { vel: 88, tir: 68, rit: 85, reg: 79, def: 78, fis: 77 },
    rating: 81,
    playerImageUrl: 'https://i.postimg.cc/XqK0fpK0/11-NAHUEL-MOLINA.png',
    clubImageUrl: 'https://i.postimg.cc/VvWqJg4v/atletico-madrid.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 12,
    name: 'Franco Armani',
    position: 'POR',
    rarity: 'rare',
    stats: { vel: 80, tir: 40, rit: 82, reg: 45, def: 85, fis: 81 },
    rating: 82,
    playerImageUrl: 'https://i.postimg.cc/Jz2SBNwk/12-FRANCO-ARMANI.png',
    clubImageUrl: 'https://i.postimg.cc/ydpB8yv2/river-plate.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 13,
    name: 'L. Martínez',
    position: 'DEF',
    rarity: 'rare',
    stats: { vel: 79, tir: 62, rit: 80, reg: 73, def: 87, fis: 84 },
    rating: 84,
    playerImageUrl: 'https://i.postimg.cc/QMQ0m19C/13-LISANDRO-MARTINEZ.png',
    clubImageUrl: 'https://i.postimg.cc/Wp4v8gG8/man-utd.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 14,
    name: 'Lionel Messi',
    position: 'DEL',
    rarity: 'epic',
    stats: { vel: 85, tir: 92, rit: 90, reg: 96, def: 38, fis: 72 },
    rating: 94,
    playerImageUrl: 'https://i.postimg.cc/cJ8wBnHj/14-LIONEL-MESSI.png',
    clubImageUrl: 'https://i.postimg.cc/C1pTsmQn/inter-miami.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 15,
    name: 'Kylian Mbappé',
    position: 'DEL',
    rarity: 'legendary',
    stats: { vel: 99, tir: 92, rit: 95, reg: 94, def: 45, fis: 85 },
    rating: 95,
    playerImageUrl: 'https://i.postimg.cc/qqpKrDLV/15-kylian-mbappe.png',
    clubImageUrl: 'https://i.postimg.cc/J4D6V3kG/psg.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg',
  },
  {
    id: 16,
    name: 'Hugo Lloris',
    position: 'POR',
    rarity: 'epic',
    stats: { vel: 85, tir: 45, rit: 84, reg: 50, def: 88, fis: 80 },
    rating: 87,
    playerImageUrl: 'https://i.postimg.cc/9XBTbVmW/16-HUGO-LLORIS.png',
    clubImageUrl: 'https://i.postimg.cc/zX8ZgGgD/tottenham.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg',
  },
  {
    id: 17,
    name: 'Virgil van Dijk',
    position: 'DEF',
    rarity: 'legendary',
    stats: { vel: 82, tir: 65, rit: 85, reg: 75, def: 94, fis: 90 },
    rating: 91,
    playerImageUrl: 'https://i.postimg.cc/bw42rwTR/17-VIRGI-VAN-DIJK.png',
    clubImageUrl: 'https://i.postimg.cc/44rGvQ1p/liverpool.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg',
  },
  {
    id: 18,
    name: 'Messi',
    position: 'DEL',
    rarity: 'CRACKS',
    stats: { vel: 95, tir: 98, rit: 96, reg: 99, def: 50, fis: 85 },
    rating: 99,
    playerImageUrl: 'https://i.postimg.cc/x8qzqJWt/18-MESSI.png',
    clubImageUrl: 'https://i.postimg.cc/C1pTsmQn/inter-miami.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 19,
    name: 'Di Maria',
    position: 'DEL',
    rarity: 'CRACKS',
    stats: { vel: 94, tir: 90, rit: 92, reg: 95, def: 60, fis: 80 },
    rating: 94,
    playerImageUrl: 'https://i.postimg.cc/50WmT3QL/19-DI-MARIA.png',
    clubImageUrl: 'https://i.postimg.cc/0j7bS3Jj/benfica.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 20,
    name: 'C. Caniggia',
    position: 'DEL',
    rarity: 'LEYENDA MUNDIAL',
    stats: { vel: 99, tir: 88, rit: 95, reg: 90, def: 50, fis: 82 },
    rating: 93,
    playerImageUrl: 'https://i.postimg.cc/DwMhrWJt/20-CLAUDIO-CANNIGIA.png',
    clubImageUrl: 'https://i.postimg.cc/ydpB8yv2/river-plate.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
];

    