export type CardStats = {
  vel: number; // Velocidad
  tir: number; // Tiro
  rit: number; // Ritmo
  reg: number; // Regate
  def: number; // Defensa
  fis: number; // Físico
};

export type Card = {
  id: number;
  name: string;
  position: 'POR' | 'DEF' | 'MED' | 'DEL';
  rarity: 'common' | 'rare' | 'epic' | 'legendary' | 'hero' | 'CRACKS' | 'LEYENDA MUNDIAL';
  stats: CardStats;
  rating: number;
  playerImageUrl: string;
  clubImageUrl: string;
  countryImageUrl: string;
};

export const allCards: Card[] = [
  {
    id: 1,
    name: 'Dibu Martinez',
    position: 'POR',
    rarity: 'legendary',
    stats: { vel: 88, tir: 52, rit: 85, reg: 58, def: 90, fis: 85 },
    rating: 90,
    playerImageUrl: '/images/CARTA_DIBU.png',
    clubImageUrl: '/images/aston-villa.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 2,
    name: 'Lionel Messi',
    position: 'DEL',
    rarity: 'legendary',
    stats: { vel: 87, tir: 95, rit: 92, reg: 98, def: 40, fis: 75 },
    rating: 97,
    playerImageUrl: '/images/CARTA_MESSI.png',
    clubImageUrl: '/images/inter-miami.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 3,
    name: 'Ángel Di María',
    position: 'DEL',
    rarity: 'epic',
    stats: { vel: 90, tir: 85, rit: 88, reg: 92, def: 50, fis: 72 },
    rating: 88,
    playerImageUrl: '/images/3_ANGEL_DI_MARIA.png',
    clubImageUrl: '/images/benfica.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 4,
    name: 'Julián Álvarez',
    position: 'DEL',
    rarity: 'rare',
    stats: { vel: 88, tir: 86, rit: 87, reg: 84, def: 55, fis: 78 },
    rating: 84,
    playerImageUrl: '/images/4_julian_alvarez.png',
    clubImageUrl: '/images/man-city.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 5,
    name: 'Rodrigo De Paul',
    position: 'MED',
    rarity: 'rare',
    stats: { vel: 82, tir: 78, rit: 85, reg: 84, def: 75, fis: 88 },
    rating: 84,
    playerImageUrl: '/images/5_DE_PAUL.png',
    clubImageUrl: '/images/atletico-madrid.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 6,
    name: 'Leandro Paredes',
    position: 'MED',
    rarity: 'common',
    stats: { vel: 70, tir: 80, rit: 75, reg: 81, def: 78, fis: 80 },
    rating: 81,
    playerImageUrl: '/images/6_LEANDRO_PADREDES.png',
    clubImageUrl: '/images/as-roma.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 7,
    name: 'Enzo Fernández',
    position: 'MED',
    rarity: 'rare',
    stats: { vel: 80, tir: 82, rit: 83, reg: 86, def: 75, fis: 81 },
    rating: 85,
    playerImageUrl: '/images/7_ENZO_FERNADNEZ.png',
    clubImageUrl: '/images/chelsea.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 8,
    name: 'A. Mac Allister',
    position: 'MED',
    rarity: 'rare',
    stats: { vel: 81, tir: 83, rit: 82, reg: 85, def: 72, fis: 79 },
    rating: 84,
    playerImageUrl: '/images/8_MACLISTTER.png',
    clubImageUrl: '/images/liverpool.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 9,
    name: 'Cuti Romero',
    position: 'DEF',
    rarity: 'epic',
    stats: { vel: 80, tir: 55, rit: 82, reg: 70, def: 89, fis: 86 },
    rating: 86,
    playerImageUrl: '/images/9_cuti_romero.png',
    clubImageUrl: '/images/tottenham.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 10,
    name: 'N. Otamendi',
    position: 'DEF',
    rarity: 'rare',
    stats: { vel: 72, tir: 60, rit: 75, reg: 68, def: 88, fis: 87 },
    rating: 83,
    playerImageUrl: '/images/10_NICOLAS_OTAMENDI.png',
    clubImageUrl: '/images/benfica.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 11,
    name: 'Nahuel Molina',
    position: 'DEF',
    rarity: 'common',
    stats: { vel: 88, tir: 68, rit: 85, reg: 79, def: 78, fis: 77 },
    rating: 81,
    playerImageUrl: '/images/11_NAHUEL_MOLINA.png',
    clubImageUrl: '/images/atletico-madrid.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 12,
    name: 'Franco Armani',
    position: 'POR',
    rarity: 'rare',
    stats: { vel: 80, tir: 40, rit: 82, reg: 45, def: 85, fis: 81 },
    rating: 82,
    playerImageUrl: '/images/12_FRANCO_ARMANI.png',
    clubImageUrl: '/images/river-plate.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 13,
    name: 'L. Martínez',
    position: 'DEF',
    rarity: 'rare',
    stats: { vel: 79, tir: 62, rit: 80, reg: 73, def: 87, fis: 84 },
    rating: 84,
    playerImageUrl: '/images/13_LISANDRO_MARTINEZ.png',
    clubImageUrl: '/images/man-utd.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 14,
    name: 'Lionel Messi',
    position: 'DEL',
    rarity: 'epic',
    stats: { vel: 85, tir: 92, rit: 90, reg: 96, def: 38, fis: 72 },
    rating: 94,
    playerImageUrl: '/images/14_LIONEL_MESSI.png',
    clubImageUrl: '/images/inter-miami.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 15,
    name: 'Kylian Mbappé',
    position: 'DEL',
    rarity: 'legendary',
    stats: { vel: 99, tir: 92, rit: 95, reg: 94, def: 45, fis: 85 },
    rating: 95,
    playerImageUrl: '/images/15_kylian_mbappe.png',
    clubImageUrl: '/images/psg.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg',
  },
  {
    id: 16,
    name: 'Hugo Lloris',
    position: 'POR',
    rarity: 'epic',
    stats: { vel: 85, tir: 45, rit: 84, reg: 50, def: 88, fis: 80 },
    rating: 87,
    playerImageUrl: '/images/16_HUGO_LLORIS.png',
    clubImageUrl: '/images/tottenham.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg',
  },
  {
    id: 17,
    name: 'Virgil van Dijk',
    position: 'DEF',
    rarity: 'legendary',
    stats: { vel: 82, tir: 65, rit: 85, reg: 75, def: 94, fis: 90 },
    rating: 91,
    playerImageUrl: '/images/17_VIRGI_VAN_DIJK.png',
    clubImageUrl: '/images/liverpool.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg',
  },
  {
    id: 18,
    name: 'Messi',
    position: 'DEL',
    rarity: 'CRACKS',
    stats: { vel: 95, tir: 98, rit: 96, reg: 99, def: 50, fis: 85 },
    rating: 99,
    playerImageUrl: '/images/18_MESSI.png',
    clubImageUrl: '/images/inter-miami.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 19,
    name: 'Di Maria',
    position: 'DEL',
    rarity: 'CRACKS',
    stats: { vel: 94, tir: 90, rit: 92, reg: 95, def: 60, fis: 80 },
    rating: 94,
    playerImageUrl: '/images/19_DI_MARIA.png',
    clubImageUrl: '/images/benfica.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
  {
    id: 20,
    name: 'C. Caniggia',
    position: 'DEL',
    rarity: 'LEYENDA MUNDIAL',
    stats: { vel: 99, tir: 88, rit: 95, reg: 90, def: 50, fis: 82 },
    rating: 93,
    playerImageUrl: '/images/20_CLAUDIO_CANNIGIA.png',
    clubImageUrl: '/images/river-plate.png',
    countryImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
  },
];
